FROM fedora:latest AS base

RUN dnf -y update && \
    dnf -y install httpd && \
    dnf clean all

EXPOSE 80
CMD ["httpd", "-D", "FOREGROUND"]

FROM base AS website1
COPY website1.html /var/www/html/index.html
LABEL website="1"

FROM base AS website2
COPY website2.html /var/www/html/index.html
LABEL website="2"
